### ISSUE TITLE
Unit testing with Buildalyzer

### ISSUE THREAD

**Issue by richardwerkman** [daveaglick/Buildalyzer#102]
## Introduction
Hi, I'm using Buildalyzer in [Stryker.NET](https://github.com/stryker-mutator/stryker-net). The implementation is great and solves a lot of our problems with analyzing .net core projects. But I'm having trouble with writing good unit tests for the parts that use buildalyzer output.

## Issue
In our unit tests we can't mock/instantiate AnalyzerResult objects. Troughout our whole application we need to have this objects available. If all unit tests have to analyze a whole project to get a AnalyzerResult object to only read one property, our unit tests will get overly complicated for a seemingly easy task.

For example:
``` csharp
var testProjectAnalyzerResultMock = new Mock<AnalyzerResult>(MockBehavior.Strict);
var mockedBuildalyzerResult = testProjectAnalyzerResultMock.Object;
```
Throws an exception since AnalyserResult doesn't expose an parameterless constructor. It would be great if mocking AnalyzerResults was possible. 

## Request
Define interfaces for all public classes like `AnalyzerResult`, `AnalyzerManager` and `ProjectAnalyzer`. Also make sure a parameterless constructor is available and `public`.

**Comment by daveaglick** [comment]
This is a good idea. I'll define interfaces for the key parts, but I'm unlikely to change or add constructors to the actual implementations. The API is carefully designed and I don't want to introduce public members just for the purpose of testing or mocking. Will having interfaces serve that purpose (I.e., mock the interface instead of the implementation)?

**Comment by richardwerkman** [comment]
Interfaces sure would help! You can see [here](https://github.com/stryker-mutator/stryker-net/blob/93ca8a5f37e76885ded1c2f4cb7c12123081cc9d/src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs#L34) what we did to mock the analyzer result ourselves. It would be nice to be able to do the mocking in our unit test project and not in our main project.

The parameterless constructor is not needed I guess. I'm not sure why I requested that in the first place. Mocking an interface doesn't need an implementation anyway. 

Sounds great that this will be picked up! Thanks for this great project, it helps stryker a lot!
