### ISSUE TITLE
MSBuild v16 issues

### ISSUE THREAD

**Issue by sapsari** [daveaglick/Buildalyzer#107]
I have been using Buildalyzer v0.5 for a while on my Ubuntu. I did update my system and things got broken.

First I got file not found error for "/usr/share/dotnet/sdk/2.2.203/15.0/Microsoft.Common.props", which is actually at "/usr/share/dotnet/sdk/2.2.203/Current/Microsoft.Common.props". Tried to bypass this error by copying "Current" directory with name "15.0", then got this error:

Target PrepareForBuild:
    Creating directory "Temp/bin/Debug/netcoreapp2.0/".
Target _GenerateCompileDependencyCache:
    /usr/share/dotnet/sdk/2.2.203/Microsoft.Common.CurrentVersion.targets(3434,7): error MSB4064: The "IgnoreCase" parameter is not supported by the "Hash" task. Verify the parameter exists on the task, and it is a settable public instance property.
    /usr/share/dotnet/sdk/2.2.203/Microsoft.Common.CurrentVersion.targets(3432,5): error MSB4063: The "Hash" task could not be initialized with its input parameters. 
Done building target "_GenerateCompileDependencyCache" in project "Assembly-CSharp.csproj" -- FAILED.

Also installed .Net Core 2.2 for hope of fixing some version mismatch, but it didn't help either.

https://github.com/Microsoft/msbuild/issues/3778 this might help with the first error

https://developercommunity.visualstudio.com/content/problem/516497/cant-create-or-add-projects-in-solution.html for the second error I tried cleaning GAC for Microsoft.Build.* as suggested but nothing changed.

Also tried to update Buildalyzer to v2.2, but after update my app freezes after calling AnalyzerManager.GetWorkspace()

Can anyone confirm Buildalyzer v2.2 works fine on Linux or OSX with the latest .Net Core and MSBuild? Then I will focus on my updating issues.

My dotnet --info log

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.203/
--- End breadcrumb write 0

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
Gathering SDK locations in [/usr/share/dotnet]
Found SDK version [2.1.603]
Found SDK version [2.2.203]
  2.1.603 [/usr/share/dotnet/sdk]
  2.2.203 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
Gathering FX locations in [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
Found FX version [2.1.10]
Found FX version [2.2.4]
Gathering FX locations in [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Found FX version [2.1.10]
Found FX version [2.2.4]
Gathering FX locations in [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Found FX version [2.1.10]
Found FX version [2.2.4]
  Microsoft.AspNetCore.All 2.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by daveaglick** [comment]
Version 2.3.0 was just released. The test suite which includes running Buildalyzer on simple test projects as well as several actual open source projects is run on all three platforms in CI: https://dev.azure.com/daveaglick/Buildalyzer/_build Based on the large set of tests, I'm reasonably confident it works well on Linux and OSX, though there are always edge cases with something this complex.

What I can tell you is Buildalyzer versions before 2.x shouldn't be used. They used a totally different mechanism to interact with MSBuild that ended up being unstable and caused lots of problems. MSBuild integration was rewritten for 2.x and works much, much better now.

**Comment by sapsari** [comment]
Finally I have solved the update issues and can confirm that Buildalyzer 2.3.0 works fine with MSBuild16 on Ubuntu18.04
