### ISSUE TITLE
Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by ionoy** [daveaglick/Buildalyzer#117]
Hi!

I'm trying to use Buildalyzer in my project. Here is the code:

```
var solutionFile = new FileInfo(@"c:\Projects\LiveSharp\XamarinFormsTest.sln");
var manager = new AnalyzerManager(solutionFile.FullName, new AnalyzerManagerOptions
{
    LoggerFactory = new LogFactory()
});
var ws = manager.GetWorkspace();
```

The build output is following

```
Started process 30872: "dotnet" "C:\Program Files\dotnet\sdk\2.2.102\MSBuild.dll" /noconsolelogger /restore /target:Clean;Build /property:ProvideCommandLineArgs="true";GenerateResourceMSBuildArchitecture="CurrentArchitecture";DesignTimeBuild="true";BuildProjectReferences="false";SkipCompilerExecution="true";DisableRarCache="true";AutoGenerateBindingRedirects="false";CopyBuildOutputToOutputDirectory="false";CopyOutputSymbolsToOutputDirectory="false";SkipCopyBuildProduct="true";AddModules="false";UseCommonOutputDirectory="true";GeneratePackageOnBuild="false";NonExistentFile="__NonExistentSubDir__\__NonExistentFile__";SolutionDir="c:\Projects\LiveSharp" /l:BuildalyzerLogger,"C:\Projects\LiveSharp\src\LiveSharp.Workspace\bin\Debug\net472\Buildalyzer.Logger.dll";1868;False "c:\Projects\LiveSharp\test\XamarinFormsTest\XamarinFormsTest\XamarinFormsTest.csproj"

The "LiveSharp.Build.PlatformCheckTask" task could not be loaded from the assembly c:\Projects\LiveSharp\build\LiveSharp.Build.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Process 30872 exited with code 1
```

`LiveSharp.Build.PlatformCheckTask` is my custom task that references Microsoft.Build.Utilities.
```
    <Reference Include="Microsoft.Build.Framework" />
    <Reference Include="Microsoft.Build.Utilities.v4.0" />
```

Is this expected behavior or am I missing something?

**Comment by ionoy** [comment]
Ok, I fixed it by passing `Preference = EnvironmentPreference.Framework` to `Build`

If I understand the issue correctly, it is difficult to always correctly guess if it's a `dotnet` or `MSBuild.exe` build, right? How does VS decide which toolset to use?

Thanks!

**Comment by daveaglick** [comment]
Great - glad you got it working!

> it is difficult to always correctly guess if it's a dotnet or MSBuild.exe build, right?

You have no idea 🤣. That's why the most recent version of Buildalyzer actually shells out to the CLI and captures logging events over a pipe - it was just too hard to try and reverse engineer where all the MSBuild libraries should come from for a given build and if it should use the Framework vs. Core versions.

Even then Buildalyzer has to guess which CLI command to run. Here's where that happens: https://github.com/daveaglick/Buildalyzer/blob/c83a348678931e6931449254a602abb2aa4cb252/src/Buildalyzer/Environment/EnvironmentFactory.cs#L39-L52.

> How does VS decide which toolset to use?

![](https://media2.giphy.com/media/12NUbkX6p4xOO4/giphy.gif)

**Comment by ionoy** [comment]
Thanks for the explanation!

I might be wrong, but it seems like **currently** VS defaults to MSBuild and using Core when Core-specific target frameworks are encountered (`netcoreapp*`). Maybe we should ask someone from MS to comment on that.

**Comment by daveaglick** [comment]
The code around platform identification has continued to mature since this issue was discussed and I think it's either resolved or no longer relevant. Please comment or open a new issue if that's incorrect and you're still having trouble.
