### ISSUE TITLE
Does Buildalyzer supports .net website projects?

### ISSUE THREAD

**Issue by nandhinithirugnanam** [daveaglick/Buildalyzer#119]
Website projects doesn't have .csproj file, how can I build website projects using buildalyzer. 
```
AnalyzerManager analyzerManager = new AnalyzerManager(solutionPath);
var projects = analyzerManager.Projects; //Project count is zero as it is a website project
```

It will be really great if buildalyzer could support website project as well.

**Comment by daveaglick** [comment]
As far as I know, non csproj are not currently supported. It partly depends on how different the project files and MSBuild arguments are as to how easy such support would be. I'm not very familiar with website projects - do those use the new csproj format or the legacy one? Do you know if they're compiled through MSBuild?

**Comment by nandhinithirugnanam** [comment]
ASP.Net website projects don't have any csproj file. 
ASP.Net website projects can be compiled using MSBuild having the .sln file path as an argument instead of csproj file path.

**Comment by daveaglick** [comment]
I'm going to go ahead and close this as out of scope (at least for the time being). I don't have the bandwidth to support some of the more exotic MSBuild project types if they're not already supported, though I'm happy to add support if someone from the community wants to add it (like we recently had done for `.fsproj` projects).
