### ISSUE TITLE
LogWriter explicitly filters out the interesting log

### ISSUE THREAD

**Issue by MeikTranel** [daveaglick/Buildalyzer#121]
Basically i'm using Buildalyzer to E2E test my package. Now i'm trying to add diagnostics as a feature and i would like to do some testing around log output, but it seems that the internal commandbuilder forces the `/noconsolelogger` switch, which disables pretty much all regular build output. Doing this:

```csharp
using(var logWriter = new StringWriter())
{
    var analyzerManager = new AnalyzerManager(
        new AnalyzerManagerOptions()
        {
            LogWriter = logWriter
        }
    );
...
```
results in:

```console
Started process 7460: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe"  /noconsolelogger /restore /target:Clean;Build /property:ProvideCommandLineArgs="true";GenerateResourceMSBuildArchitecture="CurrentArchitecture";="";NonExistentFile="__NonExistentSubDir__\__NonExistentFile__";ResolveNuGetPackages="true";SolutionDir="C:\Users\trane\AppData\Local\Temp\dikhqqry.1l1" /l:BuildalyzerLogger,"D:\Development\NXPorts\tests\NXPorts.Tests\bin\Debug\net48\Buildalyzer.Logger.dll";2444;False "C:\Users\trane\AppData\Local\Temp\dikhqqry.1l1\sdknet48.csproj"
Microsoft (R) Build Engine version 16.5.0-preview-19562-03+d72e25031 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1006: Property is not valid.
Switch: =
For switch syntax, type "MSBuild -help"
Process 7460 exited with code 1
```

**Comment by daveaglick** [comment]
Buildalyzer disconnects the console logger because it attaches it's own logger (which gets raw logging events over a pipe for higher fidelity). With both loggers attached the builds tend to slow down since MSBuild has to send events to both.

There's a couple things you could do - first I would see if attaching a `TextWriter` gets you the data you need:
```
StringWriter log = new StringWriter();
AnalyzerManager manager = new AnalyzerManager(
    "Foo.sln",
    new AnalyzerManagerOptions
    {
        LogWriter = log
    });
// ...
```

If that's not sufficient you can attach [your own binary logger or console logger](https://docs.microsoft.com/en-us/visualstudio/msbuild/build-loggers) using `AnalyzerManager.AddBuildLogger()`. This will trigger Buildalyzer receiving _all_ MSBuild events over the pipe and forwarding them to any of your attached loggers. Doing it this way ensures events are only sent once from MSBuild to Buildalyzer and then Buildalyzer forwards them to all attached loggers.

**Comment by MeikTranel** [comment]
There is no Analyzer.AddBuildLogger tho? 😄

**Comment by MeikTranel** [comment]
```csharp
public (AnalyzerResults AnalyzerResults, string log) Build(string projectFilePath, bool designTime = false)
{
    using(var logWriter = new StringWriter())
    {
        var projectAnalyzer = new AnalyzerManager().GetProject(projectFilePath);

        projectAnalyzer.AddBuildLogger(
            new ConsoleLogger(
                Microsoft.Build.Framework.LoggerVerbosity.Normal,
                (string m) => logWriter.Write(m),
                (ConsoleColor c) => { },
                () => { }
            )
        );

        var analyzerResults = projectAnalyzer.Build(
            new EnvironmentOptions()
            {
                DesignTime = designTime
            }
        );
        return (analyzerResults, logWriter.ToString());
    }
}
```

Stuff works A+. There are some smart people working on MSBuild, that's for damn sure 😄

**Comment by daveaglick** [comment]
> There are some smart people working on MSBuild, that's for damn sure

That's the truth - so many developers only get an opportunity to scratch the surface. There's _a lot_ going on behind the scenes of our builds :).

**Comment by MeikTranel** [comment]
I like how neat the delegate parameters work. Well i'm served. Feel free to close the issue unless of course you want to track any work with this 😄

**Comment by daveaglick** [comment]
Awesome - I'll close the issue, but please do let me know how you progress, especially if you hit any other roadblocks.
