### ISSUE TITLE
How to authorize to private nuget feed

### ISSUE THREAD

**Issue by MiroslavMikus** [daveaglick/Buildalyzer#122]
Hey, we are using our private nuget feed. I'm gettings 'fail' log because of failed authentification.

![image](https://user-images.githubusercontent.com/29312172/70420050-12590900-1a67-11ea-96d9-c9de05ca2ca5.png)

Q1: Is there something I can do?
Q2: Do I need this private feed, do I just miss some transitive nuget dependencies in the results, or is there something more to know about?

Thank you in advice

**Comment by daveaglick** [comment]
Since Buildalyzer essentially shells out to either `msbuild ...` or `dotnet build ...` depending on the type of project, whatever normally works in those environments should work with Buildalyzer too. More specifically, I've have success putting a `nuget.config` at the root of the project with content like:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="MySource" value="https://pkgs.dev.azure.com/foo/_packaging/Bar/nuget/v2" />
  </packageSources>
  <packageSourceCredentials>
    <MySource>
      <add key="Username" value="..." />
      <add key="ClearTextPassword" value="..." />
    </MySource>
  </packageSourceCredentials>
</configuration>
```

**Comment by MiroslavMikus** [comment]
Thank you, 
I'm are already using `nuget.config` , it runs visual studio 2019 just fine. Looks like the problem is in the `CredentialProvider`. I have just tried msbuild with cmd. Same error.

So the answer to the first question would be 'problem between monitor and chair' :)
The second question, do I miss some important data in my results?

Thanks for your time 👍

**Comment by daveaglick** [comment]
> The second question, do I miss some important data in my results?

Maybe - especially if the dependency is required for compilation. Buildalyzer is primarily a tool for intercepting logging events from MSBuild and aggregating them in a way that's easier to work with from code. So if MSBuild isn't able to build the project, then the events that it produces (and Buildalyzer intercepts) aren't going to be reflective of a normal, successful build.

**Comment by MiroslavMikus** [comment]
Many thanks, I will close the Issue.

**Comment by daveaglick** [comment]
No problem, happy to help! Let me know how you get along.

**Comment by MiroslavMikus** [comment]
Hey @daveaglick ,
it runs now, as assumed, the problem was in the credential provider, so just refreshing the credentials does fix the issue :)

Here are my steps:

## Setup nuget.exe

This is for the package.config format

```
Set-Location (Join-path (Get-ChildItem Env:LocalAppData).Value "NuGet\CredentialProviders")
Start-Process CredentialEnrollmentManager.exe -ArgumentList @("-U https://<feed-url>/nuget/v3/index.json");
```
You should get prompt for the credentials.

## Setup dotnet.exe
This is for the newer package.reference 

1. [Here](https://github.com/microsoft/artifacts-credprovider) ist the docu for dotnet.exe credentail-provider
2. [Here](https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1)  is the installer helper for Windows platform
3. You should get output like this:
![image](https://user-images.githubusercontent.com/29312172/70503666-33cbfa80-1b24-11ea-935d-1b925b58f21e.png)
So just jump to the website and copy-paste the code.
3. And do not forget to run the interactive restore `dotnet restore --interactive` in any root project *(with the package.reference format)* folder

**Comment by daveaglick** [comment]
Thanks for the follow-up - this will be helpful if anyone else comes back here looking to do something similar.
