### ISSUE TITLE
Support solution loading

### ISSUE THREAD

**Issue by kentcb** [daveaglick/Buildalyzer#13]
My scenario requires that I take any solution and introspect upon projects within. However, this is currently not possible with Buildalyzer because it does not support solution loading.

It would be 💯 AMAZING 🎉 if Buildalyzer could be given any .sln file and analyze it for the consumer, surfacing all projects within.

**Comment by daveaglick** [comment]
Ask and you shall receive :smile:. This will go out with the next release. Implemented by passing the solution path as the first argument of the `AnalyzerManager` constructor.

**Comment by kentcb** [comment]
This is _awesome_ news and I am unreasonably excited 🏆

**Comment by JosephWoodward** [comment]
Nice one @daveaglick 😄
