### ISSUE TITLE
Cannot load solution containing solution folders

### ISSUE THREAD

**Issue by kentcb** [daveaglick/Buildalyzer#14]
Code:
```C#
// initialPath: "C:\Users\Kent\Repository\XXX\Src\XXX.sln"
var manager = new AnalyzerManager(initialPath);
```
Results in:
```
System.ArgumentException: 'The path C:\Users\Kent\Repository\XXX\Src\Platform could not be found.'
```
The solution includes a solution folder in it called "Platform":
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Platform", "Platform", "{43E194F0-7558-486E-AADA-A1DBB8855359}"
EndProject
```

**Comment by JosephWoodward** [comment]
This #15 change fixes this issue 👍

**Comment by JosephWoodward** [comment]
Looks like @daveaglick's just released a new version to NuGet including the fix @kentcb

**Comment by kentcb** [comment]
@JosephWoodward just got around to trying this, and can confirm that the solution now loads correctly 👍 

I've run into another issue, which I'll open a separate issue for.
