### ISSUE TITLE
The SolutionDir property is different from the MSBulid output 

### ISSUE THREAD

**Issue by laurenceSaes** [daveaglick/Buildalyzer#147]
The SolutionDir property does not end with a directory separator. This is different than how MSBuild sets this property: 

![image](https://user-images.githubusercontent.com/518177/95077709-3e3f2c80-0714-11eb-9b09-c767a458294f.png)

In ProjectAnalyzer the Path.GetDirectoryName API is used. This does not append the directory with the directory separator.

**Comment by daveaglick** [comment]
Note: fix is in PR #148

**Comment by daveaglick** [comment]
Thanks!
