### ISSUE TITLE
WPF Custom Control libraries are not handled correctly

### ISSUE THREAD

**Issue by markrendle** [daveaglick/Buildalyzer#179]
I've opened a PR for this: #178

Something weird happens during the build of a WPF Custom Control library, a temporary project is generated or something, which breaks Buildalyzer. Looks to be down to the stack handling in `EventProcessor`.

**Comment by daveaglick** [comment]
So many project types 🤯. Thanks for running this one down, it's been years since I've done WPF so I never would have found this. Resolved by #178
