### ISSUE TITLE
ProjectReferences could be duplicated, which ends up with ThrowArgumentItemNullOrDuplicateException

### ISSUE THREAD

**Issue by Mingxue008** [daveaglick/Buildalyzer#203]
Buildalyzer is only parsing the csproj files, and doesn't ensure that ProjectReferences to be distinct when accessed by users. After users get their AnalyseResult and try to add that result back into an AdhocWorkspace, which will call Roslyn ProjectInfo.Create() API and trigger ThrowArgumentItemNullOrDuplicateException by Roslyn default behavior. We would expect ProjectReferences to be distinct even users somehow edit their csproj files and accidently duplicated them.

**Comment by Mingxue008** [comment]
It should be a simple fix, and I could do the fix, but I don't have permission to create PR. What's the policy to contribute to Buildalyzer repo?

**Comment by daveaglick** [comment]
Thanks a bunch for taking the lead on getting this fixed @Mingxue008! Resolved in #204.

**Comment by Mingxue008** [comment]
@daveaglick any update on the release of Buidalyzer?

**Comment by daveaglick** [comment]
@Mingxue008 I actually totally forget this wasn't released yet! Thanks for the reminder, pushing the release button now.

**Comment by Mingxue008** [comment]
Thanks for the release, much appreciated.
