### ISSUE TITLE
Nuget Package 4.1.4 Availbility

### ISSUE THREAD

**Issue by toneill818** [daveaglick/Buildalyzer#208]
In the RELEASE.md, it shows the latest as 4.1.4, but it is not present on nuget.org or in the GitHub releases page. Is there a 4.1.4 release?

**Comment by daveaglick** [comment]
It'll roll out to NuGet soon (maybe even today). I've got one more feature to get in.

I update the release file as features are added and PRs are merged to make sure it stays up to date (especially if anyone is building from source). Then it gets baked into the package upon the official release. The version on NuGet is always the latest officially released though (consider the comments in the release file as pre-release until it goes out to NuGet).

**Comment by toneill818** [comment]
Thanks!
