### ISSUE TITLE
Symbol analysis not working against solution

### ISSUE THREAD

**Issue by kentcb** [daveaglick/Buildalyzer#21]
My code for loading a solution looks like this:

```C#
var manager = new AnalyzerManager(initialPath);
var solution = manager.GetWorkspace().CurrentSolution;
```

Whilst this seems to take a _lot_ longer than it did previously under Roslyn, it does eventually give me what is ostensibly a working `Solution`.

However, when I try and analyze symbols within the compilation, I see nothing. Specifically, [this code](https://github.com/kentcb/PCLMock/blob/master/Src/PCLMock.CodeGeneration/Generator.cs#L1079-L1105) (which starts with the global namespace symbol) never finds any other symbol.

Interestingly, if I look at the `ProjectReferences`, it is empty, even for projects in the solution that definitely reference other projects in the solution. It's not clear to me whether this is the underlying cause.

On a hunch, I tried doing this after creating my `AnalyzerManager`:

```C#
foreach (var p in manager.Projects)
{
    p.Value.Compile();
}
```

But that did not help.

**Comment by JosephWoodward** [comment]
I don't suppose you have a repo where I could try replicate this, or any replication steps?

**Comment by kentcb** [comment]
@JosephWoodward hmm, that will be tricky. I'm using the `netstandard` branch of my open source [PCLMock](https://github.com/kentcb/PCLMock) project, but I am running it against proprietary code. Chances are if you do the same thing against your own SDK-style/netstandard solution you'll see the same problem.

Steps:
1. Clone PCLMock and switch to the `netstandard` branch
2. Open PCLMock in VS2017
3. Set *PCLMock.CodeGeneration.Console* as the startup project
4. Change the properties of the *PCLMock.CodeGeneration.Console* per the screenshot below
5. Set a breakpoint in *Generator.cs* line 69 (in `GenerateMocksAsync`)
6. Run it!

When the breakpoint is hit, you'll see the `project` has no referenced projects.

Please let me know if this helps. If I have to create a separate repro project to run against, I will find the time to do so.

![image](https://user-images.githubusercontent.com/1901832/31970612-1ebf5038-b960-11e7-9a7b-1aa9bfbf2a23.png)

**Comment by kentcb** [comment]
OK, forget the above repro instructions - I've recreated this in a very simple project, attached.

Instructions:
1. Unzip
2. Open _BuildalyzerRepro.sln_
3. Run the app

All it does is load another solution (bundled) and output the project names and their project references. It gets the names right, but not the reference from the _ViewModels_ project to the _Utility_ project.

Digging deeper now - just wanted to post this ahead of my investigations.

[BuildalyzerRepro.zip](https://github.com/daveaglick/Buildalyzer/files/1429209/BuildalyzerRepro.zip)

**Comment by kentcb** [comment]
And literally the second thing I tried worked. First I tried using latest Buildalyzer (same behavior), then I tried making my executing project a netcore console app instead of a netfx one. That worked.

**Comment by daveaglick** [comment]
Cool - that's a perfect repro, thanks. I'll take a look as soon as I get a chance.

**Comment by daveaglick** [comment]
Buildalyzer 1.0.0 was released to NuGet last night. Can you please try it out when you get the chance and let me know the status of this issue?

FYI - the Buildalyzer 1.0.0 API has changed significantly. Revised documentation is forthcoming, but I wanted to get the release out there ASAP. Hopefully you'll be able to figure out the differences, but if not the source code of the tests is a good place to look or wait until better docs are out next week.

**Comment by kentcb** [comment]
I can no longer repro this with `1.0.0`. Thanks!
