### ISSUE TITLE
AWS porting assistant crashes on Buildalyzer.ProjectAnalyzer.Build

### ISSUE THREAD

**Issue by WiseSewaTroll** [daveaglick/Buildalyzer#218]
Hi,
I am getting a weird msbuild exception which I believe comes from the Build method in ProjectAnalyzer.

![image](https://user-images.githubusercontent.com/24988423/200869198-e8c8154e-1fda-47bb-a1cd-75819fc225f4.png)

I have tried providing more env variables but the exception remains. Can you please help get rid of this exception?

**Comment by WiseSewaTroll** [comment]
Fixed by reinstalling VS 2022

**Comment by daveaglick** [comment]
Glad that did the trick! The best bugs are ones that fix themselves :)
