### ISSUE TITLE
Looking For A New Maintainer

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Buildalyzer#247]
As much as it pains me to write this, it's time to see if I can find Buildalyzer a new, more productive home. Despite my best intentions over the last couple years, I think it's become obvious to anyone engaged with this project that I just don't have the personal bandwidth to give it the attention it requires. This decision hasn't been made lightly - I've been thinking about how to move forward on several of my projects for a long time as my kids get older and my family takes priority for an increasing portion my downtime. In this case, I think the best thing I can do it set the project free.

Which brings me to this issue: Buildalyzer needs a new maintainer. I'm looking to completely divest myself of this project and transfer the repository to someone else who's able to do a better job triaging issues, reviewing and merging PRs, and generally keeping it up to date. I don't want to be in the middle of progress, so I think the best thing is to move completely out of the way.

Some of the more recent active users include @Corniel, @0xced, and @phmonte. Likewise I also know that stryker-mutator is one of the bigger consumers (cc @rouke-broersma, @dupdob, etc.).

Are any of you (or anyone else out there) interested in taking over Buildalyzer? If so, drop me a line and we'll figure out the best way to transfer the project!

![image](https://github.com/daveaglick/Buildalyzer/assets/1020407/97896326-8826-4933-b105-e542164b38c4)

**Comment by phmonte** [comment]
Hello, I wrote you an email.

**Comment by Corniel** [comment]
I'm more than willing to actively support the continuation of this wonderful project. I'm not sure, if I'm the best person to take the lead.

**Comment by richardwerkman** [comment]
Great to hear we can keep on using this project! Thanks @phmonte for stepping up :)
