### ISSUE TITLE
Outputs get cleaned

### ISSUE THREAD

**Issue by dfederm** [daveaglick/Buildalyzer#38]
It seems to kind of defeat the purpose of a design-time build to do a clean beforehand. If the project were previously built via normal methods, the outputs will disappear after doing a design-time build.

It seems like at the very least this should be a flag,

**Comment by daveaglick** [comment]
IIRC there was a reason why I ended up forcing a clean - something about .NET Core builds getting confused if the obj directory was hanging around from a previous build. I'd need to go back and take a closer look to be sure.

I'd be fine making it a switch though - the default behavior would need to stay the same so we don't break anyone.

**Comment by dfederm** [comment]
Thanks for the context. PR with the addition of a flag is out :)
