### ISSUE TITLE
GetReferences returns null although the project does reference other assemblies

### ISSUE THREAD

**Issue by bobuva** [daveaglick/Buildalyzer#46]
Buildalyzer is a really nice OSS project, by the way. I'm just getting started with it, and am having a problem. Thanks in advance!

I've got a `.NET Core 2.1 preview` project whose `.csproj` looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentCommandLineParser" Version="1.4.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>
</Project>
```

My code to display references looks like this:

```
                AnalyzerManager manager = new AnalyzerManager();
                Buildalyzer.ProjectAnalyzer analyzer = manager.GetProject(projectFilename);
                Project proj = analyzer.Load();
                IEnumerable<string> references = analyzer.GetReferences();
                if (references == null)
                {
                    Console.WriteLine("No references found. Quitting.");
                    return;
                }

                foreach (var r in references)
                    Console.WriteLine(r);
```

It always returns `null` for references. Is this not supported for `.NET Core 2.*` yet?

Bob

**Comment by daveaglick** [comment]
Thanks for the report. Buildalyzer should be working under all .NET Core 2.x scenarios _except preview SDKs_. I'm working on the problem with previews, but as far as I can tell it should only appear on systems at runtime when a preview SDK is installed. Does this describe your situation? Typically this failure exhibits itself as compilation failures which can be seen in the Buildalyzer log output - are you able to confirm if you see any errors in the log (you can pass in a logger to Buildalyzer or grab the string log)?

**Comment by bobuva** [comment]
I am using .NET Core 2.1 preview with the SDKs that come with it. For some reason, when I try to see the log output in a StringWriter (see below) I don't get anything. Even when I write it out in a finally clause.

```
            StringBuilder sb = new StringBuilder();
            StringWriter writer = new StringWriter(sb);
            AnalyzerManagerOptions options = new AnalyzerManagerOptions();
            options.LogWriter = writer;
```

**Comment by daveaglick** [comment]
Buildalyzer 1.0.0 was released to NuGet last night. Can you please try it out when you get the chance and let me know the status of this issue?

FYI - the Buildalyzer 1.0.0 API has changed significantly. Revised documentation is forthcoming, but I wanted to get the release out there ASAP. Hopefully you'll be able to figure out the differences, but if not the source code of the tests is a good place to look or wait until better docs are out next week.

**Comment by bobuva** [comment]
@daveaglick I ran it again using `Buildalyzer 1.0.0` and it worked! My only code change was from

```
IEnumerable<string> references = analyzer.GetReferences();
```
to
```
IEnumerable<string> references = analyzer.Build().GetReferences();
```

Note that I also tried
```
IEnumerable<string> references = analyzer.Build().GetProjectReferences();
```
but that returned an empty collection.

**Comment by daveaglick** [comment]
Great! I'll go ahead and close this then - feel free to open a new issue if you have any other problems.
