### ISSUE TITLE
Possible problems with latest SDK not including dependencies alongside Microsoft.NET.Build.Tasks

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Buildalyzer#49]
See https://github.com/dotnet/sdk/issues/2108

If there's no easy resolution within MSBuild and the SDK does stop shipping the assemblies alongside, then we could potentially crawl up the SDK folders when assembly resolution fails:

```
private System.Reflection.Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
{
    // Crawl up from the _buildEnvironment.ToolsPath (or _buildEnvironment.SDKsPath?) to see if the missing assemblies can be located
}
```

This would probably need to go in `AnalyzerManager` so that the hooks only get added once. We'd also want to use a static flag to keep track of whether we've already added the hooks in the case of multiple managers. May need to consider making `AnalyzerManager` disposable too and unregister the hooks on disposal.

**Comment by ltcmelo** [comment]
Hi @daveaglick, do you intent to act on this plan any time soon? I guess the issue persists with 2.1...

**Comment by daveaglick** [comment]
Yep, not sure when I'll be circling back to Buildalyzer though (I tend to work my projects in sprints, so might be a couple weeks until I do work on this one). TBH, I haven't looked at the final 2.1 release to see if they did indeed remove the assemblies. If so, then this approach may be our only option.

**Comment by daveaglick** [comment]
@ltcmelo A new version 0.5.0 is hitting NuGet now - can you please take it for a spin and let me know if it resolves this issue for you?

**Comment by ltcmelo** [comment]
@daveaglick, thanks for the heads up. I will try to give it a try this week and I'll let you know.

**Comment by ltcmelo** [comment]
Hi @daveaglick, it seems that 0.5.0 fixed the issue, indeed. A colleague @vaiocosl verified and it works. Thanks!

**Comment by daveaglick** [comment]
Thanks for confirming!
