### ISSUE TITLE
Add extension library for Roslyn workspaces

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Buildalyzer#5]
Add an extension library that can create an `AdhocWorkspace` (or add a Roslyn `Project` to an existing workspace) given a Buildalyzer `ProjectAnalyzer`

**Comment by daveaglick** [comment]
@JosephWoodward May want to take a look at this, I know you were talking about creating Workspaces from the build output earlier. Going to release it to NuGet, but my guess is that it'll probably need a couple more iterations to cover every case.

**Comment by JosephWoodward** [comment]
Nice, I'll give it a look later.
