### ISSUE TITLE
Add link to Buildalyzer blog post(s)

### ISSUE THREAD

**Issue by tjrobinson** [daveaglick/Buildalyzer#50]
I came across this project before I read [this blog post](https://daveaglick.com/posts/running-a-design-time-build-with-msbuild-apis) and have to admit I was very impressed but also very confused about what Buildalyzer was for. The blog post clears it up, so I think would be worth linking to from the readme?

**Comment by daveaglick** [comment]
Thanks for the suggestion - I've (finally) added the blog posts to the readme.
