### ISSUE TITLE
Strong name signing of Buildalyzer?

### ISSUE THREAD

**Issue by SabotageAndi** [daveaglick/Buildalyzer#51]
Hi

I am one of the maintainer of SpecFlow (https://github.com/techtalk/SpecFlow) and we want to use Buildalyzer to add .NET Standard/Core 2.0 to SpecFlow.
Our project is used by a lot of enterprises and they somehow like strong name signing. So we are signing our stuff also with a strong name.
Buildalyzer is currently not strong named signed. So that we can use it, we would need Buildalayzer strong named signed.

Would this be possible? If we provide a PR for that, would it be merged?

**Comment by daveaglick** [comment]
I've been thinking about this and I've decided not to strong name Buildalyzer. Here's the thinking:

- Tools exist for strong-naming after the fact. There's https://github.com/dsplaisted/strongnamer and https://github.com/oising/strongnaming for starters.
- Buildalyzer can be easily built from source and a strong name applied at that point.
- Strong naming is viral so there's the potential for issues with my dependencies as well as for consumers.
- And probably most importantly, it's just not something I have the bandwidth to support. I have limited time and too many projects as it is - this would just add _one more thing_ to the set of things I need to work on and support.

Sorry - that's probably not what you wanted to hear. I'm still super-interested in helping you get Buildalyzer working in SpecFlow so let me know if there's anything else I can do to help!

**Comment by SabotageAndi** [comment]
@daveaglick I understand your decision, if SpecFlow wasn't already strong name signed, I wouldn't add it now.

Thanks for your offer to help, but we recognized we can get everything we need on information with our MSBuild task and so we have no need anymore to read the project files.
Sorry that I forgot to close this issue, as we realized we don't need it anymore.
