### ISSUE TITLE
VS Live Unit Testing

### ISSUE THREAD

**Issue by bhugot** [daveaglick/Buildalyzer#64]
Hello,

Firs thanks for the job.
I have some problem when running tests with Live Unit Testing as it's not using CscCommandLineArgs. So the project has no document and no reference.

I m going to investigate a bit further on this. So I can compare Items from a run with CscCommandLineArgs and without.

**Comment by daveaglick** [comment]
I just published Buildalyzer 2.0 which runs MSBuild out-of-process (as opposed to the old way of running it via MSBuild APIs). In general, if you can build it Buildalyzer should now be able to build it. Given how drastically different this new technique is, I'm closing all existing bug reports.

Please try the new version and if you're still having problems, please open a new issue.
