### ISSUE TITLE
Missing 'NuGet' dependencies when ran on macos

### ISSUE THREAD

**Issue by pellet** [daveaglick/Buildalyzer#71]
Buildalyzer was crashing out from missing dependencies until I added in the following packages:
- NuGet.Build.Tasks
- NuGet.Common
- NuGet.ProjectModel.
It would throw an exception at runtime when trying to restore a project's dependencies, these dependencies might need to be added to buildalyzer for it to run smoothly under macos(this could be due to macos needing to use mono instead of dotnet?).

**Comment by daveaglick** [comment]
I just published Buildalyzer 2.0 which runs MSBuild out-of-process (as opposed to the old way of running it via MSBuild APIs). In general, if you can build it Buildalyzer should now be able to build it. Given how drastically different this new technique is, I'm closing all existing bug reports.

Please try the new version and if you're still having problems, please open a new issue.
