### ISSUE TITLE
Features in .csproj are ignored.

### ISSUE THREAD

**Issue by Nic007** [daveaglick/Buildalyzer#72]
I am trying to use the "Flow-Analysis"  which should be added to a .csproj like this

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <Features>Flow-Analysis</Features>
  </PropertyGroup>
```

However when I try to use your library like this:

```
AnalyzerManager manager = new AnalyzerManager();
 ProjectAnalyzer analyzer = manager.GetProject(@"path/to/my/project.csproj");
AdhocWorkspace workspace = analyzer.GetWorkspace();
var project = workspace.CurrentSolution.Projects.First();
System.Console.WriteLine(project.ParseOptions.Features.Count);
```

The output will be 0, the feature is not added to my project.

Some features like the ControlFlowGraph need those to be used

Ex: http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/ControlFlowGraph.cs line 74
```
if (!operation.Syntax.SyntaxTree.Options.Features.ContainsKey("flow-analysis"))
{
    throw new InvalidOperationException(CodeAnalysisResources.FlowAnalysisFeatureDisabled);
}
```

**Comment by daveaglick** [comment]
I just published Buildalyzer 2.0 which runs MSBuild out-of-process (as opposed to the old way of running it via MSBuild APIs). In general, if you can build it Buildalyzer should now be able to build it. Given how drastically different this new technique is, I'm closing all existing bug reports.

Please try the new version and if you're still having problems, please open a new issue.
