### ISSUE TITLE
Throw Exception When Inner Build Fails

### ISSUE THREAD

**Issue by patearl** [daveaglick/Buildalyzer#79]
If the BuildTargets process ends with a non-zero error code, the system should collect any output (seems to end up on StdOut instead of StdErr for no apparent reason) and throw an exception with the contents of the output.

Right now it just returns empty results even though there has clearly been an error and that error details should be propagated to the calling code somehow.

**Comment by daveaglick** [comment]
I think you can get what you need by attaching a logger - by default the stdout of the child process is logged when one is attached:

```
StringWriter log = new StringWriter();
AnalyzerManagerOptions options = new AnalyzerManagerOptions
{
    LogWriter = log
});
AnalyzerManager manager = new AnalyzerManager(path, options);
// ...
// check log.ToString() after build for any error messages
```

Let me know if that does what you need...

**Comment by patearl** [comment]
Well, it doesn't really solve the intent of "if things are failing then indicate as much". But that's not strictly necessary to solve our use case.

However, when we enable the logger we now get this strange exception:

Open in IDE
C:\Users\MrBuild\.nuget\packages\pleasantmodeller.generator\5.1.16\build\PleasantModeller.Generator.targets(36, 5): error MSB4018: The "ModelGeneratorTask" task failed unexpectedly.
System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.
Parameter name: ticks
   at System.DateTime..ctor(Int64 ticks, DateTimeKind kind)
   at Microsoft.Build.Logging.BuildEventArgsReader.ReadDateTime()
   at Microsoft.Build.Logging.BuildEventArgsReader.ReadBuildEventArgsFields()
   at Microsoft.Build.Logging.BuildEventArgsReader.ReadBuildMessageEventArgs()
   at Microsoft.Build.Logging.BuildEventArgsReader.Read()
   at MsBuildPipeLogger.BuildEventArgsReaderProxy.Read()
   at MsBuildPipeLogger.PipeLoggerServer`1.Read()
   at Buildalyzer.ProjectAnalyzer.BuildTargets(BuildEnvironment buildEnvironment, String targetFramework, String[] targetsToBuild, AnalyzerResults results)

**Comment by patearl** [comment]
Looking at that stack trace, it doesn't seem related to the logger. I think it might be due to using a BuildEnvironment for "net461". I'll see what I can dig up.

**Comment by patearl** [comment]
That date error is generated on only one of our build machines. I imagine it probably has an old version of something.

The logging output actually works.

**Comment by patearl** [comment]
I see that some things can fail and some things can succeed. I no longer wish for this particular change.
