### ISSUE TITLE
Is there an alternative to `$(NuGetPackageRoot)`?

### ISSUE THREAD

**Issue by ltcmelo** [daveaglick/Buildalyzer#81]
Hi @daveaglick ,

thanks for the re-work on MSBuild handling. I've updated and I'll give it a try. But while I can build the project locally, on our CI we have problems due to `$(NuGetPackageRoot)`. I quickly googled for this problem and I found out that, indeed, this [location can be inconsistent](https://github.com/daveaglick/Buildalyzer/issues/new).

Given that I've already run in a plenty of issue due to NuGet inconsistencies on non-Windows systems: different files (`~/.nuget/NuGet.config`, `~/.config/NuGet.config`, `~/.config/nuget.config`) and behavior between `dotnet nuget`, `nuget.exe`, MONO's nuget, it'd be good to avoid such dependency. Right now, I have a blocking CI (Jenkins) pipeline error "Could not find MsBuildPipeLogger.Logger files" which doesn't even seem to be an actual build error.

Do you seen an alternative?

**Comment by daveaglick** [comment]
I'm actually working on this exact problem - you'll notice a bunch of trail-and-error around the project file in my latest commits. I see the same thing in Linux builds on AppVeyor, so trying to work past it. I'd like to get my own CI to do xplat builds and tests.

The odd thing is that the `NuGetPackageRoot` does look like a valid location - on AppVeyor it's set to `/home/appveyor/.nuget/packages/`, but apparently that's not where restore is actually putting the packages.

Hopefully I'll get this figured out pretty soon.

**Comment by ltcmelo** [comment]
Maybe you're running into the problems I mentioned above. In our team, we discovered different setups, due to varying behavior between Microsoft's dotnet nuget restore, MONO's restore, and nuget.exe restore. In the end, we get around by either deleting (and not using) one of the NuGet.config files or specifying which config file is to be used upon a restore.

**Comment by ltcmelo** [comment]
Just to let you know, @daveaglick, that your case-sensitivity change worked for our CI. I can't yet say whether it'll work on every setup we have, but I'll keep you informed.

**Comment by daveaglick** [comment]
Awesome! You beat me to it :smile:

I'm working through some integration test failures now, mostly due to .NET Core being unable to build desktop target frameworks. Think I'm getting pretty close to a full Linux build and test in CI.

Please do let me know if you hit any other issues on your non-Windows CI servers.

**Comment by daveaglick** [comment]
I think this is solved - my own Linux AppVeyor builds have been mostly reliable (I get occasional intermittent failures but I don't think they're related to this - probably more like a pipe issue).

Going to close this - please do open a new issue if it looks like this wasn't solved after all.
