### ISSUE TITLE
Saw on Reddit, this is cool but...

### ISSUE THREAD

**Issue by ryantheleach** [daveaglick/Buildalyzer#95]
In order to promote it better, do you know any use cases that people have used it for? Child libraries?

Adding these to the site / readme would be more enticing to people considering using it, so they can see if their idea already exists, or if anyone already consumes this library.

It also goes a ton of way of generating trust for your project, if you can list several users.

**Comment by Mobrockers** [comment]
We are trying to incorporate buildalyzer in https://github.com/stryker-mutator , A dotnet core and hopefully soon dotnet full framework mutation testing tool.

**Comment by ryantheleach** [comment]
Seems to have picked up a little more steam then when I last saw it.

**Comment by daveaglick** [comment]
> Seems to have picked up a little more steam then when I last saw it.

Indeed - it's now a core part of [Wyam](https://wyam.io) as well as several other notable projects and I'm committed to supporting and evolving it for the foreseeable future.
