### ISSUE TITLE
BuildAlyzer throwing an exception.

### ISSUE THREAD

**Issue by KCarterSr** [daveaglick/Buildalyzer#97]
I'm not getting buildalyzer to work. In a simple app with only to lines of code, the second line causes an exception. 
Seems like maybe something is going on in your logging code. Here's a couple of exceptions thrown using two different .Net Frameworks.

By the way I get the exceptions no matter which project file of the projects in the solution I use.

Thanks
K. Carter Sr.

namespace ConsoleApp2
{
     using Buildalyzer;
     using Buildalyzer.Workspaces;

    class Program
    {
        static void Main(string[] args)
        {
                                   AnalyzerManager manager = new AnalyzerManager();
         EXCEPTION THROWN HERE --> AnalyzerResults results = manager.Analyze(@"D:\Documents\Starter Template\C. W. Matthews Functionality Test Application (Windows Forms)\@ C. W. Matthews Functionality Test Application (Windows Forms).csproj");
        }
    }

THIS IS THE EXCEPTION THROWN ON A .NET CORE 2.0 or a .Net Standard 2.0 PROJECT
------------------------------------------------------------------------------

An unhandled exception of type 'System.IO.InvalidDataException' occurred in System.IO.Compression.dll
The archive entry was compressed using an unsupported compression method.

System.IO.Compression.dll!System.IO.Compression.Inflater.Inflate(System.IO.Compression.ZLibNative.FlushCode flushCode) Line 216
	at E:\A\_work\2431\s\corefx\src\System.IO.Compression\src\System\IO\Compression\DeflateZLib\Inflater.cs(216)
System.IO.Compression.dll!System.IO.Compression.Inflater.ReadInflateOutput(byte* bufPtr, int length = 4, System.IO.Compression.ZLibNative.FlushCode flushCode, out int bytesRead = 0) Line 181
	at E:\A\_work\2431\s\corefx\src\System.IO.Compression\src\System\IO\Compression\DeflateZLib\Inflater.cs(181)
System.IO.Compression.dll!System.IO.Compression.Inflater.InflateVerified(byte* bufPtr, int length) Line 73
	at E:\A\_work\2431\s\corefx\src\System.IO.Compression\src\System\IO\Compression\DeflateZLib\Inflater.cs(73)
System.IO.Compression.dll!System.IO.Compression.Inflater.Inflate(byte[] bytes, int offset, int length) Line 63
	at E:\A\_work\2431\s\corefx\src\System.IO.Compression\src\System\IO\Compression\DeflateZLib\Inflater.cs(63)
System.IO.Compression.dll!System.IO.Compression.DeflateStream.Read(byte[] array = {byte[16]}, int offset, int count = 4) Line 247
	at E:\A\_work\2431\s\corefx\src\System.IO.Compression\src\System\IO\Compression\DeflateZLib\DeflateStream.cs(247)
System.IO.Compression.dll!System.IO.Compression.GZipStream.Read(byte[] array, int offset, int count) Line 84
	at E:\A\_work\2431\s\corefx\src\System.IO.Compression\src\System\IO\Compression\GZipStream.cs(84)
System.Private.CoreLib.dll!System.IO.BinaryReader.FillBuffer(int numBytes = 4) Line 635
	at E:\A\_work\2188\s\src\mscorlib\src\System\IO\BinaryReader.cs(635)
System.Private.CoreLib.dll!System.IO.BinaryReader.ReadInt32() Line 206
	at E:\A\_work\2188\s\src\mscorlib\src\System\IO\BinaryReader.cs(206)
StructuredLogger.dll!Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(System.IO.Stream stream = {System.IO.FileStream}) Line 46
	at C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs(46)
StructuredLogger.dll!Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(string sourceFilePath = "D:\\Documents\\Starter Template\\C. W. Matthews Functionality Test Application (Windows Forms)\\@ C. W. Matthews Functionality Test Application (Windows Forms).csproj") Line 38
	at C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs(38)
Buildalyzer.dll!Buildalyzer.AnalyzerManager.Analyze(string binLogPath = "D:\\Documents\\Starter Template\\C. W. Matthews Functionality Test Application (Windows Forms)\\@ C. W. Matthews Functionality Test Application (Windows Forms).csproj", System.Collections.Generic.IEnumerable<Microsoft.Build.Framework.ILogger> buildLoggers = null)
ConsoleApp2.dll!ConsoleApp2.Program.Main(string[] args = {string[0]}) Line 14
	at D:\Documents\Starter Template\ConsoleApp2\Program.cs(14)

THIS IS THE EXCEPTION THROWN ON A .NET Framework 4.6.1 PROJECT
-------------------------------------------------------------

An unhandled exception of type 'System.IO.InvalidDataException' occurred in System.dll
The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.

System.dll!System.IO.Compression.GZipDecoder.ReadHeader(System.IO.Compression.InputBuffer input) Line 43
	at f:\dd\NDP\fx\src\sys\System\IO\compression\GZipDecoder.cs(43)
System.dll!System.IO.Compression.Inflater.Decode() Line 210
	at f:\dd\NDP\fx\src\sys\System\IO\compression\Inflater.cs(210)
System.dll!System.IO.Compression.Inflater.Inflate(byte[] bytes = {byte[16]}, int offset = 0, int length = 4) Line 166
	at f:\dd\NDP\fx\src\sys\System\IO\compression\Inflater.cs(166)
System.dll!System.IO.Compression.DeflateStream.Read(byte[] array = {byte[16]}, int offset, int count = 4) Line 318
	at f:\dd\NDP\fx\src\sys\System\IO\compression\DeflateStream.cs(318)
System.dll!System.IO.Compression.GZipStream.Read(byte[] array, int offset, int count) Line 146
	at f:\dd\NDP\fx\src\sys\System\IO\compression\GZipStream.cs(146)
mscorlib.dll!System.IO.BinaryReader.FillBuffer(int numBytes = 4) Line 574
	at f:\dd\ndp\clr\src\BCL\system\io\binaryreader.cs(574)
mscorlib.dll!System.IO.BinaryReader.ReadInt32() Line 185
	at f:\dd\ndp\clr\src\BCL\system\io\binaryreader.cs(185)
StructuredLogger.dll!Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(System.IO.Stream stream = {System.IO.FileStream}) Line 46
	at C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs(46)
StructuredLogger.dll!Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(string sourceFilePath = "D:\\Documents\\Starter Template\\C. W. Matthews Functionality Test Application (Windows Forms)\\@ C. W. Matthews Functionality Test Application (Windows Forms).csproj") Line 38
	at C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs(38)
Buildalyzer.dll!Buildalyzer.AnalyzerManager.Analyze(string binLogPath = "D:\\Documents\\Starter Template\\C. W. Matthews Functionality Test Application (Windows Forms)\\@ C. W. Matthews Functionality Test Application (Windows Forms).csproj", System.Collections.Generic.IEnumerable<Microsoft.Build.Framework.ILogger> buildLoggers = null)
ConsoleApp3.exe!ConsoleApp3.Program.Main(string[] args = {string[0]}) Line 16
	at D:\Documents\Starter Template\ConsoleApp3\Program.cs(16)

**Comment by daveaglick** [comment]
Sorry for the looooong delay. If you get a chance and this is still a problem, could you try the newly released 2.3.0 - it has a couple package updates that might help.

**Comment by daveaglick** [comment]
Since this is pretty old and there have been ongoing improvements, I'm going to assume this issue is either resolved or no longer relevant. Please comment or open a new issue if that's incorrect and you're still having trouble.
