### ISSUE TITLE
Work with project dependencies

### ISSUE THREAD

**Issue by baruchiro** [daveaglick/Buildalyzer#99]
Hi, I want to write a tool/library that provides an option to get all projects that depend on the specific project, or all projects that specific project depend on.

I thought to work with [microsoft.build.evaluation.project](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project), but is is not compiled to netstandard. So after a lot of searches and questions in SO and Microsoft forums, I came here.

What I lack here in this project is the option to ask specific project, which projects depend on him (and more easy way to get common items). What is your suggestion? Adding these abilities to this project? Or maybe create an adapter for your objects?

**Comment by daveaglick** [comment]
The project references for a given project are available as `AnalyzerResult.ProjectReferences` which contains a collection of paths to all other projects that one references. This is available after building (as opposed to just scanning the project file) because the project references can change based on MSBuild conditions, tasks, etc.

```
AnalyzerManager manager = new AnalyzerManager();
ProjectAnalyzer analyzer = manager.GetProject("project.csproj");
AnalyzerResults results = analyzer.Build();
IEnumerable<string> references = results.First().ProjectReferences;
```

Does that provide what you need?

**Comment by baruchiro** [comment]
Not really. I want to develop your similar tool, just avoid building.

Static code analysis

**Comment by daveaglick** [comment]
Then what you probably want is a parser for project files, which is mostly out of scope for Buildalyzer. Buildalyzer's job is to ask MSBuild to build a project and then report back what it did. Buildalyzer doesn't know or care about what's actually in a project file until MSBuild tells it (with a couple small exceptions like figuring out the target frameworks). With the way project files work, and especially the recent integration of NuGet tasks, the "plain text" project file almost never tells the whole story.

You might want to consider if you _really_ want to avoid building or just want to avoid a long build process. Buildalyzer attempts to perform a design-time build by default - the same kind of build that Visual Studio uses in the background while you're coding for rapid feedback. If you really don't want to do any sort of build, then Buildalyzer probably isn't the tool you need. You could consider parsing the project file with an XML parser and looking for `ProjectReference` elements.

**Comment by baruchiro** [comment]
First of all, yes, I'm not sure your tool is right for me.

Second, my problem is different, so I also required a different solution.

Thanks for the response.

**Comment by daveaglick** [comment]
Okay, I'll go ahead and close this issue then. Please do let me know if there's a way Buildalyzer can help in your scenario that's in-scope or if you have any additional problems using Buildalyzer.
